### ISSUE TITLE
SCP 173 Cell

### ISSUE THREAD

**Issue by DeaNo409** [OverlordAkise/scprp-addons#4]
The 173 Cell is not working, because there is no model in the File. The ones on Discord arent working, because ,, invalid gma file" or something. It would be really nice, if you could include the Model file too (if you have one). But your Addons are really good, keep up the good work ^^!

**Comment by Phedona** [comment]
```
--Luctus SCP173 System
--Made by OverlordAkise

--For the cage to work you need the following workshop item:
--https://steamcommunity.com/sharedfiles/filedetails/?id=951301796
```

scp_173/lua/autorun/sh_scp173.lua
