### ISSUE TITLE
SCP 939 Breaching Door Feature missing/faulty

### ISSUE THREAD

**Issue by MrNeonM** [OverlordAkise/scprp-addons#5]
In the luctus_scp939 plugin, there is no config option for unbreachable doors for 939 and in weapon_luctus_scp939.lua, it says:
`if SCP173_UNBREACHABLE[ent:GetName()] or SCP173_UNBREACHABLE[ent:MapCreationID()] then`

I tried fixing it myself somehow:

**sh_luctus_scp939_config.lua:**
```
SCP939_UNBREACHABLE = {
   ["939_CC"] = true,
   ["939_Stairs"] = true,
}
```
**weapon_luctus_scp939.lua**
```
if SCP939_UNBREACHABLE[ent:GetName()] or SCP939_UNBREACHABLE[ent:MapCreationID()] then
   DarkRP.notify(ply,1,5,"Please use '!breach' to initiate a breach!")
   return false
end
```

_But it would probably still be best to add the config option and support in the weapon file to the project itself._
If I would've been able to make a Pull request I apologize for posting this as an issue, but I'm not sure about that

**Comment by OverlordAkise** [comment]
Thanks for reporting this issue!

Seems like I forgot to add this to the config and weapon. It slipped through testing as I had SCP173 installed, which kept it from creating errors.
I fixed it now, sorry for the delay.

BR
